### ISSUE TITLE
Make campaign

### ISSUE THREAD

**Issue by redhog** [innovationgarage/ProtoSwitchBoard#6]
Start with an initial campaign

- [x] Example project
- [x] Video

**Comment by eried** [comment]
https://1drv.ms/f/s!AqORX6Fjni7DuvcN84eWmC6EHVcd7g

**Comment by eried** [comment]
https://www.youtube.com/watch?v=LH1ylxZ1n84

**Comment by redhog** [comment]
Done during Oslo week  :) Wheheeee!
